[workspace]
members = [
  "crates/stdsimd-verify",
  "crates/stdsimd",
]
exclude = [
  "crates/wasm-assert-instr-tests",
  "crates/nvptx-test"
]

[profile.release]
debug = true
opt-level = 3

[profile.bench]
debug = 1
opt-level = 3
