[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "host"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
ptx-builder = "0.4"

[dependencies]
cuda = { git = "https://github.com/japaric/cuda" }
rand = "0.3.15"