#!/bin/bash

set -e

cd /qemu/init
echo "arg is: ${1}"
cp -f $1 prog
find . | cpio --create --format='newc' --quiet | gzip > ../initrd.gz
cd ..

timeout 400s qemu-system-aarch64 \
  -m 1024 \
  -nographic \
  -kernel kernel \
  -initrd initrd.gz \
  -machine virt \
  -cpu cortex-a57 \
  -append init="/prog ${@:2}" > output 2>&1 || true

# remove kernel messages
tr -d '\r' < output | egrep -v '^\['

! grep FAILED output > /dev/null