#!/bin/bash

set -e

prog=$1

cd /qemu/init
cp -f $1 prog
find . | cpio --create --format='newc' --quiet | gzip > ../initrd.gz
cd ..

timeout 30s qemu-system-aarch64 \
  -m 1024 \
  -nographic \
  -kernel kernel \
  -initrd initrd.gz \
  -append init=/prog > output || true

# remove kernel messages
tr -d '\r' < output | egrep -v '^\['

grep PASSED output > /dev/null